In [24]:
import pandas as pd

In [25]:
data = [[1, 'Will', None], [2, 'Jane', None], [3, 'Alex', 2], [4, 'Bill', None], [5, 'Zack', 1], [6, 'Mark', 2]]
customer = pd.DataFrame(data, columns=['id', 'name', 'referee_id']).astype({'id':'Int64', 'name':'object', 'referee_id':'Int64'})

In [26]:
customer

   id  name  referee_id
0   1  Will        <NA>
1   2  Jane        <NA>
2   3  Alex           2
3   4  Bill        <NA>
4   5  Zack           1
5   6  Mark           2

In [28]:
customer[(customer['referee_id'] != 2) | (customer['referee_id'].isnull())]

   id  name  referee_id
0   1  Will        <NA>
1   2  Jane        <NA>
3   4  Bill        <NA>
4   5  Zack           1