In [1]:
import pandas as pd

In [2]:
data = [[8], [8], [3], [3], [1], [4], [5], [6]]
my_numbers = pd.DataFrame(data, columns=['num']).astype({'num':'Int64'})

In [3]:
my_numbers

   num
0    8
1    8
2    3
3    3
4    1
5    4
6    5
7    6

In [30]:
df = my_numbers.drop_duplicates(keep=False).max()

In [31]:
df = pd.DataFrame(df, columns=['num'])

In [32]:
df

     num
num    6