In [1]:
import pandas as pd

In [2]:
data = [[1, None], [2, 1], [3, 1], [4, 2], [5, 2]]
tree = pd.DataFrame(data, columns=['id', 'p_id']).astype({'id':'Int64', 'p_id':'Int64'})

In [3]:
tree

   id  p_id
0   1  <NA>
1   2     1
2   3     1
3   4     2
4   5     2

In [4]:
tree['type'] = 'Leaf'

In [5]:
tree

   id  p_id  type
0   1  <NA>  Leaf
1   2     1  Leaf
2   3     1  Leaf
3   4     2  Leaf
4   5     2  Leaf

In [11]:
tree.loc[tree['id'].isin(tree['p_id']),'type'] = 'inner'

In [12]:
tree

   id  p_id   type
0   1  <NA>  inner
1   2     1  inner
2   3     1   Leaf
3   4     2   Leaf
4   5     2   Leaf

In [15]:
tree.loc[tree['p_id'].isnull(), "type"] = 'root'

In [16]:
tree

   id  p_id   type
0   1  <NA>   root
1   2     1  inner
2   3     1   Leaf
3   4     2   Leaf
4   5     2   Leaf