In [51]:
import pandas as pd

In [52]:
data = {
    'pid': list(range(1, 30)),
    'tiv_2015': [
        224.17, 224.17, 824.61, 424.32, 424.32, 625.05, 424.32, 624.46, 425.49,
        624.46, 624.46, 225.93, 824.61, 824.61, 826.37, 824.61, 824.61, 626.81,
        224.76, 224.76, 427.25, 224.76, 424.90, 227.69, 424.90, 424.90, 828.13,
        625.05, 625.05
    ],
    'tiv_2016': [
        952.73, 900.66, 645.13, 323.66, 282.90, 243.53, 968.94, 714.13, 463.85,
        776.85, 692.71, 933.00, 786.86, 935.34, 516.10, 374.50, 924.19, 897.47,
        714.79, 681.53, 263.27, 671.80, 769.18, 830.50, 844.97, 733.35, 931.83,
        659.13, 300.16
    ],
    'lat': [
        32.4, 52.4, 72.4, 12.4, 12.4, 52.5, 72.5, 12.5, 32.5,
        12.4, 72.5, 12.5, 32.6, 52.6, 12.4, 12.6, 32.6, 52.6,
        72.6, 12.4, 32.7, 52.7, 72.7, 12.7, 12.4, 52.7, 72.8,
        12.8, 32.8
    ],
    'lon': [
        20.2, 32.7, 45.2, 7.7, 7.7, 32.8, 45.3, 7.8, 20.3,
        7.7, 45.3, 7.8, 20.3, 32.8, 7.7, 7.9, 20.4, 32.9,
        45.4, 7.7, 20.4, 32.9, 45.4, 7.9, 7.7, 32.9, 45.5,
        8.0, 20.5
    ]
}
insurance = pd.DataFrame(data, columns=['pid', 'tiv_2015', 'tiv_2016', 'lat', 'lon']).astype({'pid':'Int64', 'tiv_2015':'Float64', 'tiv_2016':'Float64', 'lat':'Float64', 'lon':'Float64'})

In [53]:
insurance

    pid  tiv_2015  tiv_2016   lat   lon
0     1    224.17    952.73  32.4  20.2
1     2    224.17    900.66  52.4  32.7
2     3    824.61    645.13  72.4  45.2
3     4    424.32    323.66  12.4   7.7
4     5    424.32     282.9  12.4   7.7
5     6    625.05    243.53  52.5  32.8
6     7    424.32    968.94  72.5  45.3
7     8    624.46    714.13  12.5   7.8
8     9    425.49    463.85  32.5  20.3
9    10    624.46    776.85  12.4   7.7
10   11    624.46    692.71  72.5  45.3
11   12    225.93     933.0  12.5   7.8
12   13    824.61    786.86  32.6  20.3
13   14    824.61    935.34  52.6  32.8
14   15    826.37     516.1  12.4   7.7
15   16    824.61     374.5  12.6   7.9
16   17    824.61    924.19  32.6  20.4
17   18    626.81    897.47  52.6  32.9
18   19    224.76    714.79  72.6  45.4
19   20    224.76    681.53  12.4   7.7
20   21    427.25    263.27  32.7  20.4
21   22    224.76     671.8  52.7  32.9
22   23     424.9    769.18  72.7  45.4
23   24    227.69     830.5  12.7   7.9
24   25     424.9    844.97  12.4   7.7
25   26     424.9    733.35  52.7  32.9
26   27    828.13    931.83  72.8  45.5
27   28    625.05    659.13  12.8   8.0
28   29    625.05    300.16  32.8  20.5

In [56]:
uni_loc = insurance.drop_duplicates(subset=['lat', 'lon'], keep=False)

In [57]:
tiv = insurance[insurance.duplicated(subset='tiv_2015', keep=False)]['tiv_2015']

In [58]:
res = uni_loc[uni_loc['tiv_2015'].isin(tiv)]

In [72]:
res['tiv_2016'].sum()

In [75]:
df = pd.DataFrame({'tiv_2016' : [round(res['tiv_2016'].sum(), 2)]})

In [76]:
df

   tiv_2016
0    8206.2