In [1]:
import pandas as pd

In [21]:
data = [[1, 'Abbot'], [2, 'Doris'], [3, 'Emerson'], [4, 'Green'], [5, 'Jeames'], [6, 'Aman']]
seat = pd.DataFrame(data, columns=['id', 'student']).astype({'id':'Int64', 'student':'object'})

In [22]:
seat

   id  student
0   1    Abbot
1   2    Doris
2   3  Emerson
3   4    Green
4   5   Jeames
5   6     Aman

In [23]:
a = list(seat['student'])

In [24]:
a

['Abbot', 'Doris', 'Emerson', 'Green', 'Jeames', 'Aman']

In [25]:
for i in range(0,len(a),2):
    if i == len(a)-1: 
        break
    tem = a[i] 
    a[i] = a[i+1]
    a[i+1] = tem

In [26]:
a

['Doris', 'Abbot', 'Green', 'Emerson', 'Aman', 'Jeames']

In [19]:
seat['student'] = a

In [20]:
seat

   id  student
0   1    Doris
1   2    Abbot
2   3    Green
3   4  Emerson
4   5   Jeames