In [1]:
import pandas as pd

In [2]:
data = [[1, 1, 0], [1, 1, 1], [1, 1, 2], [1, 2, 3], [1, 2, 4], [2, 1, 5], [2, 1, 6]]
actor_director = pd.DataFrame(data, columns=['actor_id', 'director_id', 'timestamp']).astype({'actor_id':'int64', 'director_id':'int64', 'timestamp':'int64'})

In [51]:
actor_director

   actor_id  director_id  timestamp
0         1            1          0
1         1            1          1
2         1            1          2
3         1            2          3
4         1            2          4
5         2            1          5
6         2            1          6

In [69]:
a = actor_director.groupby(['actor_id', 'director_id']).count().reset_index()

In [70]:
a

   actor_id  director_id  timestamp
0         1            1          3
1         1            2          2
2         2            1          2

In [75]:
a[a['timestamp'] >= 3][['actor_id', 'director_id']]

   actor_id  director_id
0         1            1